nome = input("Digite seu nome completo: ")
letras_maiusculas = nome.upper()
letras_minusculas = nome.lower()
letras_aotodo = len(nome.replace(" ", ""))
letras_prinome = len(nome.split()[0])
print(f"O nome com todas as letras maiúsculas é {letras_maiusculas}.")
print(f"O nome inteiro em maiusculas é {letras_minusculas}.")
print(f"Seu nome contém {letras_aotodo} caracteres.")
print(f"O seu primeiro nome tem {letras_prinome}.")